#!/bin/bash

### BEGIN INIT INFO
# Provides:             host metrics via HTTP by node_exporter
# Required-Start:
# Required-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1
# Description:          Runs prometheus node exporter to collect metrics from this host and provide them to /metrics by HTTP
# Short-Description:    Runs prometheus node exporter
### END INIT INFO

NAME="metricsd"
BIN_FILE="/usr/local/bin/node_exporter"
LOG_FILE="/var/log/${NAME}"

case "${1}" in
    start)
        daemon --name "${NAME}" -r -o "${LOG_FILE}" -X "${BIN_FILE}"
    ;;

    stop)
        daemon --name "${NAME}" --stop
    ;;

    status)
        daemon --name "${NAME}" --running
        echo "${NAME} is running: $?"
    ;;

    force-reload|restart)
        daemon --name "${NAME}" --restart
    ;;
    *)
        echo "Usage: ${0} {start|stop|restart|force-reload|status}"
        echo "Also it is good way to use (as root) command: service ${NAME} {status | start | stop | restart}"
        exit 1
    ;;
esac
