#!/bin/bash

### BEGIN INIT INFO
# Provides:             uwsgi
# Required-Start:
# Required-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1
# Description:          Runs uwsgi with config from /etc/uwsgi/uwsgi_config.ini
# Short-Description:    Runs uwsgi
### END INIT INFO

NAME="uwsgid"
CONF_FILE="/etc/uwsgid/config.ini"
BIN_FILE="/usr/local/bin/uwsgi"
LOG_FILE="/var/log/${NAME}"

case "${1}" in
    start)
        echo "Starting uwsgi as a daemon"
        daemon --name "${NAME}" -r -o "${LOG_FILE}" -X "${BIN_FILE} --emperor ${CONF_FILE}"
    ;;

    stop)
        echo "Stopping uwsgi daemon"
        daemon --name "${NAME}" --stop
    ;;

    status)
        daemon --name "${NAME}" --running
        echo "${NAME} is running: $?"
    ;;

    force-reload|restart)
        daemon --name "${NAME}" --restart
    ;;
    *)
        echo "Usage: ${0} {start|stop|restart|force-reload|status}"
	echo "Also it is good way to use (as root) command: service ${NAME} {status | start | stop | restart}"
        exit 1
    ;;
esac
