---
- name: add api user to mysql server
  mysql_user: 
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
#    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
...
