---
- name: importing mysql database
  mysql_db: 
    name: all
    state: import
    target: /vagrant/test_corp-dump.sql
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
...
