---
- name: get gpg key for mysql deb package
  apt_key: 
    keyserver: keyserver.ubuntu.com
    id: 8C718D3B5072E1F5
  become: yes
- name: add mysql apt repository to sources.list.d
  copy: 
    src: mysql.list
    dest: /etc/apt/sources.list.d/mysql.list
    owner: root
    group: root
  become: yes
- name: mysql server install
  apt: 
    update_cache: yes
    name: "mysql-server"
    state: present
  become: yes
...
