---
- name: install pip3
  apt: 
    update_cache: yes
    name: "python3-pip"
    state: "present"
  become: yes
- name: install vitrtualenv module
  pip: 
    name: virtualenv
    state: present
    # uncomment next line if python3 is not used on remote host
    # executable: pip3
  become: yes
...
