---
- name: clone project
  git: 
    repo: https://github.com/Trofogol/sample-http-api.git
    dest: "{{ project_path }}"
- name: prepare python virtual environment for api
  pip: 
    chdir: "{{ project_path }}"
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_python: python3
...
